### ISSUE TITLE
reduce default dependencies

### ISSUE THREAD

**Issue by clitic** [emarsden/dash-mpd-rs#2]
This library is super useful but requires more dependencies than required (**for parsing only**).

Main mpd parser only use **serde**, **quick-xml** and **regex** dependencies all other dependencies are used by fetch module. My proposal is that fetch module and it's dependencies should be kept under a feature and main mpd parser in the root.

anyhow can also be replaced with std::error::Error trait. For fetch feature anyhow can be optional dep.

**Comment by emarsden** [comment]
Thanks for this suggestion. I wouldn't have thought many people use only the parsing support, which is pretty simple, but I've implemented your suggestion. I'll deal with the anyhow crate (which shouldn't really be used in a library) later.
