### ISSUE TITLE
maybe consider updating deserializer (parser) and adding serializer for datetime fields to get micro/nanos precision

### ISSUE THREAD

**Issue by sbuzzard** [emarsden/dash-mpd-rs#20]
Because the `iso860` crate only includes precision down to millisecond, if an MPD is delivered with more precision date/time (as some of ours are), we lose that precision.   It would be helpful if there was a way we could maintain that precision.

**Comment by sbuzzard** [comment]
I wonder if it would be reasonable to have a feature on the library to opt into rfc3339 date/time parsing.  All the MPDs we process follow the stricter standard for date/times and that would maintain the precision as well.  The lib already serializes into that format (via use of the default chrono serializer for datetime<utc>).  Understand that by default you need to maintain iso8601 parsing to be spec compliant but if you're open to an opt-in feature for parsing, I'd be glad to PR it.

**Comment by emarsden** [comment]
Done now, thanks.
