### ISSUE TITLE
Fetch audio and video without muxing

### ISSUE THREAD

**Issue by sleepycatcoding** [emarsden/dash-mpd-rs#25]
Is there a way to download video and audio without muxing them into one file? I would like to have them as separate files.

**Comment by sleepycatcoding** [comment]
Actually I found a way to accomplish this by using `audio_only()` and `video_only()`, but this requires two requests to the manifest file. I do not know if `reqwest` caches requests to the same file.

**Comment by emarsden** [comment]
You can use `DashDownloader::new(url).keep_audio().keep_video()`. This doesn't in fact disable the muxing step but will keep the audio and video as separate files (assuming they are separate content streams).

**Comment by sleepycatcoding** [comment]
> You can use `DashDownloader::new(url).keep_audio().keep_video()`. This doesn't in fact disable the muxing step but will keep the audio and video as separate files (assuming they are separate content streams).

If I were to use `keep_audio()` and `keep_video()`, is there a way to fetch paths to the files?

**Comment by emarsden** [comment]
Indeed, there's no API to retrieve that information. Perhaps it would be better to change the interface to something like `keep_audio_as(audio-pathname)` .

**Comment by sleepycatcoding** [comment]
> Indeed, there's no API to retrieve that information. Perhaps it would be better to change the interface to something like `keep_audio_as(audio-pathname)` .

Created a draft PR for this: #26.
