### ISSUE TITLE
Add serde attribute rename="Location" to  MPD.locations field

### ISSUE THREAD

**Issue by nissy34** [emarsden/dash-mpd-rs#33]
https://github.com/emarsden/dash-mpd-rs/blob/0e543c4a0fba70a5d32bc5602b02922085fab913/src/lib.rs#L1657
The location tag in the dash schema is "Location" but in the MPD struct the field name is "locations".

The field is missing
 ```rust
 #[serde(rename = "Location", default)]
 ```

**Comment by emarsden** [comment]
Fixed, thanks!
