### ISSUE TITLE
Have bitstreamSwitching and BitstreamSwitching properties in SegmentTemplate

### ISSUE THREAD

**Issue by sbuzzard** [emarsden/dash-mpd-rs#55]
For 0.15 I noticed there's bitstreamSwitching and BitstreamSwitching properties in SegmentTemplate - that seems like a mistake?

**Comment by emarsden** [comment]
Not a mistake. The 2022 version of the specification includes these in SegmentTemplate. 

   https://standards.iso.org/ittf/PubliclyAvailableStandards/c083314_ISO_IEC%2023009-1_2022(en).zip

**Comment by sbuzzard** [comment]
oh, interesting, one's an attribute and one's a subelement.
