### ISSUE TITLE
Make reqwest features optional

### ISSUE THREAD

**Issue by holly-hacker** [emarsden/dash-mpd-rs#8]
I like to keep my binary size down and some features specified for reqwest I don't need. For example, compression and use of rustls over native-tls are features I don't need in my application and I prefer to turn those off to speed up CI and lower binary size.

Ideally, those features would be enabled by default (using default features) but opt-out for those that don't need it. Considering the next update will be a breaking release, I think now is the ideal time to introduce these changes.

**Comment by emarsden** [comment]
Handling this problem using feature flags seems a bit verbose. Presumably, each reqwest feature could be turned into a "passthrough" feature in this crate (reqwest-rustls, reqwest-proxy, reqwest-bzip, reqwest-gzip, etc.), which doesn't seem very elegant.

Isn't the binary size problem handled automatically by dead code elimination and LTO (with "lto=fat")?

(I'm not familiar with good practice guidance in this area, apologies.)

**Comment by holly-hacker** [comment]
Some feature flags only enable new APIs, but the TLS and compression related features will always include the TLS stack or send compression headers so the related code can't be eliminated.

Personally, I would have a feature for rustls and a feature for some amount of compression (probably just gzip?). The compression feature doesn't matter too much since you're either downloading mpd playlists (small plaintext files) or video/audio (already compressed data). I would enable the compression feature by default but the rustls one is up to you.

**Comment by emarsden** [comment]
OK, thanks for the suggestion. I've implemented this. Please let me know if you see possible improvements in the way it's done.

**Comment by holly-hacker** [comment]
I just tested it out and it works great when using the fetch feature! I noticed that enabling any of the reqwest-related features (eg. the default feature set) will always pull in reqwest as a dependency, which is probably not desired. It's probably best to either enable the `fetch` feature by default, or to move all reqwest-related features out of the default feature set.

**Comment by holly-hacker** [comment]
I just gave it a try and it seems to work great! Nothing else to add :)
